name: Movies

options:
  minimumXcodeGenVersion: 2.16.0
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "13.0"

fileGroups:
  - .gitignore
  - xcodegen

include:
  - path: xcodegen/ios.yml
    relativePaths: false
